### ISSUE TITLE
22 Character Limit - Optional

### ISSUE THREAD

**Issue by JimboJBaggins** [IainMNorman/elite-dangerous-ship-name-generator#1]
Hi, as Elite: Dangerous only allows 22 characters for ship names, would you be able to add an option for your awesome name generator to limit its output to 22 characters (including spaces)?

That'd be very much appreciated.

**Comment by IainMNorman** [comment]
I'll take a look at this once I have access to the beta to assess the situation.

**Comment by IainMNorman** [comment]
This has been added to the latest version.
